image: upstreamable/php-jsdelivr-api-client

# Select what we should cache
cache:
  paths:
    - vendor/
    - composer.lock

before_script:
  # Install all project dependencies
  - composer install

syntax:
  script:
    - vendor/bin/php-cs-fixer fix --diff --dry-run --config=.php_cs.php -vvv

test:
  script:
    - vendor/bin/phpunit --configuration phpunit.dist.xml

